### PR TITLE
Use setEmitMetadata for location

### PR DESCRIPTION
**Pull request by ef4**
This accompanies https://github.com/typed-ember/glint/pull/299

### CODE REVIEW

**Comment by jamescdavis** [comment]
https://github.com/typed-ember/glint/pull/299 has been released in https://github.com/typed-ember/glint/releases/tag/0.7.5 if you can update devDeps here.

**Comment by dfreeman** [comment]
To be fair it's not like there are any tests or anything for updating devDeps to affect, so we're probably fine to just merge this and spend that notional time on pulling this into the `typed-ember/glint` repo itself

**Comment by dfreeman** [comment]
Published in v0.0.4

**Comment by jamescdavis** [comment]
> it's not like there are any tests or anything

totally fair! 🙂

**Pull request merged**
